angular.module('app')
    .factory('RobotFactory', function() {

      var robots = [
      {
        name: "Tory",
        gender: "Femme",
        product: "Deus",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séducteur",
        quality: "Mystérieux",
        fault: "Jaloux",
        priceSpe: "4 300 €",
        price: "Entre 4 000 € et 5 000 €",
      },
      {
        name: "Alix",
        gender: "Neutre",
        product: "Beauty",
        eyes: "Bleu",
        hair: "Brun",
        personality: "Romantique",
        quality: "Rêveur",
        fault: "Silencieux",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Calia",
        gender: "Femme",
        product: "Beauty",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séducteur",
        quality: "Indépendant",
        fault: "Bavard",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Ripley",
        gender: "Femme",
        product: "Sidereal",
        eyes: "Bleu",
        hair: "Blond",
        personality: "Romantique",
        quality: "Mystérieux",
        fault: "Silencieux",
        priceSpe: "6 040 €",
        price: "Entre 5 000 € et 7 000 €",
      },
      {
        name: "Ryo",
        gender: "Homme",
        product: "Sidereal",
        eyes: "Noir",
        hair: "Noir",
        personality: "Aventurier",
        quality: "Joueur",
        fault: "Impulsif",
        priceSpe: "6 040 €",
        price: "Entre 5 000 € et 7 000 €",
      },
      {
        name: "Rebecca",
        gender: "Femme",
        product: "Deus",
        eyes: "Vert",
        hair: "Noir",
        personality: "Aventurier",
        quality: "Indépendant",
        fault: "Introverti",
        priceSpe: "4 300 €",
        price: "Entre 4 000 € et 5 000 €",
      },
      {
        name: "Anto",
        gender: "Homme",
        product: "Deus",
        eyes: "Violet",
        hair: "Châtain",
        personality: "Aventurier",
        quality: "Joueur",
        fault: "Jaloux",
        priceSpe: "4 300 €",
        price: "Entre 4 000 € et 5 000 €",
      },
      {
        name: "Khor",
        gender: "Neutre",
        product: "Beauty",
        eyes: "Noir",
        hair: "Brun",
        personality: "Séducteur",
        quality: "Extraverti",
        fault: "Impulsif",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Liar",
        gender: "Homme",
        product: "Beauty",
        eyes: "Noir",
        hair: "Noir",
        personality: "Romantique",
        quality: "Mystérieux",
        fault: "Jaloux",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Arwel",
        gender: "Homme",
        product: "Beauty",
        eyes: "Violet",
        hair: "Brun",
        personality: "Aventurier",
        quality: "Extraverti",
        fault: "Impulsif",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Stella",
        gender: "Femme",
        product: "Beauty",
        eyes: "Violet",
        hair: "Châtain",
        personality: "Séducteur",
        quality: "Rêveur",
        fault: "Introverti",
        priceSpe: "3 700 €",
        price: "Entre 3 000 € et 4 000 €",
      },
      {
        name: "Alia",
        gender: "Femme",
        product: "Sidereal",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séductrice",
        quality: "Mystérieux",
        fault: "Silencieux",
        priceSpe: "6 040 €",
        price: "Entre 5 000 € et 7 000 €",
      },
    ];
      return robots;
    });
