angular.module('app')
    .factory('RobotFactory', function() {

      var robots = [
      {
        name: "Tory",
        gender: "Féminin",
        product: "Deus",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séducteur",
        quality: "Mystérieux",
        fault: "Jaloux",
        price: "4 300 €",
      },
      {
        name: "Alix",
        gender: "Neutre",
        product: "Beauty",
        eyes: "Bleue",
        hair: "Brun",
        personality: "Romantique",
        quality: "Rêveur",
        fault: "Silencieux",
        price: "3 700 €",
      },
      {
        name: "Calia",
        gender: "Féminin",
        product: "Beauty",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séducteur",
        quality: "Indépendant",
        fault: "Bavard",
        price: "3 700 €",
      },
      {
        name: "Ripley",
        gender: "Féminin",
        product: "Sidereal",
        eyes: "Bleu",
        hair: "Blond",
        personality: "Romantique",
        quality: "Mystérieux",
        fault: "Silencieux",
        price: "6 040 €",
      },
      {
        name: "Ryo",
        gender: "Masculin",
        product: "Sidereal",
        eyes: "Noir",
        hair: "Noir",
        personality: "Aventurier",
        quality: "Joueur",
        fault: "Impulsif",
        price: "6 040 €",
      },
      {
        name: "Rebecca",
        gender: "Féminin",
        product: "Deus",
        eyes: "Vert",
        hair: "Noir",
        personality: "Aventurier",
        quality: "Indépendant",
        fault: "Introverti",
        price: "4 300 €",
      },
      {
        name: "Anto",
        gender: "Masculin",
        product: "Deus",
        eyes: "Violet",
        hair: "châtain",
        personality: "Aventurier",
        quality: "Joueur",
        fault: "Jaloux",
        price: "4 300 €",
      },
      {
        name: "Khor",
        gender: "Neutre",
        product: "Beauty",
        eyes: "Noir",
        hair: "Brun",
        personality: "Séducteur",
        quality: "Extraverti",
        fault: "Impulsif",
        price: "3 700 €",
      },
      {
        name: "Liar",
        gender: "Masculin",
        product: "Beauty",
        eyes: "Noir",
        hair: "Noir",
        personality: "Romantique",
        quality: "Mystérieux",
        fault: "Jaloux",
        price: "3 700 €",
      },
      {
        name: "Arwel",
        gender: "Masculin",
        product: "Beauty",
        eyes: "Violet",
        hair: "Brun",
        personality: "Aventurier",
        quality: "Extraverti",
        fault: "Impulsif",
        price: "3 700 €",
      },
      {
        name: "Stella",
        gender: "Féminin",
        product: "Beauty",
        eyes: "Violet",
        hair: "Châtain",
        personality: "Séducteur",
        quality: "Rêveur",
        fault: "Introverti",
        price: "3 700 €",
      },
      {
        name: "Alia",
        gender: "Féminin",
        product: "Sidereal",
        eyes: "Noir",
        hair: "Noir",
        personality: "Séductrice",
        quality: "Mystérieux",
        fault: "Silencieux",
        price: "6 040 €",
      },
    ];
      return robots;
    });
